import js from '@eslint/js';

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  console: 'readonly',
  performance: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  Image: 'readonly',
  HTMLElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLInputElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  TouchEvent: 'readonly',
  PointerEvent: 'readonly',
  MutationObserver: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  matchMedia: 'readonly',
  getComputedStyle: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  indexedDB: 'readonly',
  AudioContext: 'readonly',
  webkitAudioContext: 'readonly',
  Audio: 'readonly',
  WebGLRenderingContext: 'readonly',
  WebGL2RenderingContext: 'readonly',
  Worker: 'readonly',
  SharedWorker: 'readonly',
  postMessage: 'readonly',
  crypto: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  __BUILD_TIME__: 'readonly',
  __COMMIT_SHA__: 'readonly',
  __DEV__: 'readonly',
  __DRIVE_CLIENT_ID__: 'readonly',
  // Runtime window-attached globals from the game's compatibility layer
  G_EVENT: 'readonly',
  gameNodes: 'readonly',
  gameplayFlags: 'readonly',
  metaState: 'readonly',
  showToast: 'readonly',
  registerUpdateTopHUD: 'readonly',
  logTL: 'readonly',
  linkVersion: 'writable',
  spawnShock: 'readonly',
  _sourceNodeCount: 'writable',
  _lastSignalCalmness: 'writable',
};

const nodeTestGlobals = {
  global: 'readonly',
  process: 'readonly',
  Buffer: 'readonly',
  describe: 'readonly',
  it: 'readonly',
  test: 'readonly',
  expect: 'readonly',
  beforeAll: 'readonly',
  afterAll: 'readonly',
  beforeEach: 'readonly',
  afterEach: 'readonly',
  vi: 'readonly',
};

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: browserGlobals,
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-undef': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-unreachable': 'warn',
      'semi': ['warn', 'always'],
      'prefer-const': 'warn',
      'no-var': 'error',
    },
  },
  {
    files: ['src/tests/**/*.js'],
    languageOptions: {
      globals: { ...browserGlobals, ...nodeTestGlobals },
    },
  },
];
